### ISSUE TITLE
what is the root password?

### ISSUE THREAD

**Issue by wdehoog** [ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one#13]
When having an adb shell and trying dmesg it says permission denied. When trying 'sudo dmesg' the root password is asked but the standard one 'phablet' is not accepted.

**Comment by mariogrip** [comment]
This should fix that: https://github.com/ubuntu-touch-oneplus-one/ubuntu-touch-for-oneplus-one/issues/12#issuecomment-82644862

**Comment by haseeb-heaven** [comment]
@wdehoog : Just use these commands to access shell as root
sudo bash (may ask for one time password your log in password)
sudo -i

this works for me hope it will work for you aswell

**Comment by wdehoog** [comment]
My problem is I do not know the password. During the installation it is not asked for so I tried what I thought to be the default one ('phablet') but that one does not work

**Comment by haseeb-heaven** [comment]
@wdehoog its says permission denied because the file doesnt have the right persmission. Change the file Permission by chmod command.. 
ex : chmod 777 MyFile

List of Permissions of Linux.. 
0 – no permission
1 – execute
2 – write
3 – write and execute
4 – read
5 – read and execute
6 – read and write
7 – read, write, and execute

**Comment by wdehoog** [comment]
Thanks for helping. The password is the passcode I set. I did not expect that.
